version: '3'

services:
  puppet:
    hostname: puppet
    image: puppet/puppetserver
    ports:
      - 8140:8140
    environment:
      # DNS_ALT_NAMES must be set before starting the stack the first time,
      # and must list all the names under which the puppetserver can be
      # reached. 'puppet' must be one of them, otherwise puppetdb won't be
      # able to get a cert. Add other names as a comma-separated list
      - DNS_ALT_NAMES
      - PUPPETDB_SERVER_URLS=https://puppetdb:8081
    volumes:
      - ./volumes/code:/etc/puppetlabs/code/
      - ./volumes/puppet:/etc/puppetlabs/puppet/
      - ./volumes/serverdata:/opt/puppetlabs/server/data/puppetserver/
    networks:
      default:

  postgres:
    environment:
      - POSTGRES_PASSWORD=puppetdb
      - POSTGRES_USER=puppetdb
      - POSTGRES_DB=puppetdb
    expose:
      - 5432
    # volumes can only be overriden by *target*, not *source*
    # so define them in .override.yml and .windows.yml since target varies
    # either /var/lib/postgresql/data/ on Linux or c:\data on Windows
    # https://docs.docker.com/compose/extends/#adding-and-overriding-configuration
    networks:
      default:

  puppetdb:
    hostname: puppetdb
    image: puppet/puppetdb
    environment:
      - PUPPETDB_PASSWORD=puppetdb
      - PUPPETDB_USER=puppetdb
    ports:
      - 8080
      - 8081
    depends_on:
      - postgres
      - puppet
    volumes:
      - ./volumes/puppetdb/ssl:/etc/puppetlabs/puppet/ssl/
    networks:
      default:

networks:
  default:
