apiVersion: v2
name: puppetserver-helm-chart
type: application
version: 3.0.0
appVersion: 6.9.2
description: Puppet automates the delivery and operation of software.
keywords: ["puppet", "puppetserver", "automation", "iac", "infrastructure", "cm", "ci", "cd"]
home: https://puppet.com/
icon: https://secure.gravatar.com/avatar/fdd009b7c1ec96e088b389f773e87aec.jpg?s=80&r=g&d=mm
sources:
- https://github.com/puppetlabs/pupperware/
maintainers:
- name: Xtigyro
  email: miroslav.hadzhiev@gmail.com
- name: scottcressi
  email: scottcressi@gmail.com
- name: underscorgan
  email: morgan@puppet.com
- name: slconley
  email: slconley@gmail.com
engine: gotpl
kubeVersion: ">=1.10.0-0"
