# Default values for puppetserver.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## Puppet Server Configuration
##
puppetserver:
  name: puppetserver
  image: puppet/puppetserver
  tag: 6.9.0
  pullPolicy: IfNotPresent
  ## Horizontal Scaling
  ## Optional deployment of multiple Puppet Server Compilers
  multiCompilers:
    enabled: false
    ## Horizontal Pod Manual Scaling
    ## Set the desired number of Puppet Server Compilers
    manualScaling:
      compilers: 3
    ## Horizontal Pod Autoscaling
    ## Automatically scales the number of pods (compilers)
    ## based on observed CPU/memory utilization
    ## Note that the metrics must be provided by
    ## additionally deployed metrics server of your choice
    autoScaling:
      enabled: false
      minCompilers: 1
      maxCompilers: 5
      cpuUtilizationPercentage: 80
      memoryUtilizationPercentage: 80
  resources: {}
  #  requests:
  #    memory: 768Mi
  #    cpu: 500m
  #  limits:
  #    memory: 1Gi
  #    cpu: 750m
  ## Additional puppetserver container environment variables
  extraEnv: {}
  ## Use pre-generated Puppet certs in `./init/puppet-certs`
  ## Check README for related use cases
  preGeneratedCertsJob:
    enabled: false
    jobDeadline: 300
  ## Fully qualified domain names (FQDN's) to register
  ## the Puppet Server to be internally reachable via DNS.
  ## That is necessary to configure "certname" and "server" in `puppet.conf`.
  ## Required by Puppet server CA CLI application.
  ## "serverName" is mandatory and pre-set to "puppet".
  ## "alternateServerNames" is optional.
  ##
  fqdns:
    alternateServerNames: ""   # Comma-separated
  ## The usage of a TCP/Network LB type is strongly preferable
  ## Please check the `README.md` for more information
  ## Exemplary annotations for few cloud providers
  service:
    type: ClusterIP
    ## The LB type (network protocol) for some cloud providers must be set here.
    ports:
      puppetserver:
        port: 8140
      #  protocol: TCP
    annotations: {}
    #  service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    #  service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    #  service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    #  cloud.google.com/load-balancer-type: "Internal"
    #  service.kubernetes.io/ibm-load-balancer-cloud-provider-ip-type: "private"
    labels: {}
    loadBalancerIP: ""
  ingress:
    ## If true, Puppet Server Ingress will be created
    ##
    enabled: false
    ## Puppet Server Ingress annotations
    ##
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    ## Puppet Server Ingress additional labels
    ##
    extraLabels: {}
    ## Puppet Server Ingress hostnames with optional path
    ## Must be provided if Ingress is enabled
    ##
    hosts: []
    #   - puppet.domain.com
    #   - domain.com/puppet
    ## Puppet Server Ingress TLS configuration
    ## Secrets must be manually created in the namespace
    ##
    tls: []
    #   - secretName: puppet-server-tls
    #     hosts:
    #       - puppet.domain.com

  ## The pattern of managing Hieradata in a separate repository is
  ## both common and acceptable. Doing so provides the ability to decouple
  ## the management of configuration data from that of the Puppet code base.
  ## A separate Hieradata Repo can be included in the "hiera" section in this file.
  ##
  puppeturl: ""   # git@github.com:$SOMEUSER/puppet.git

## r10k Repo Configuration
##
r10k:
  name: r10k
  image: puppet/r10k
  tag: 3.3.3
  pullPolicy: IfNotPresent
  ## Affinity for "r10k" pod assignment
  ## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
  ## Note that the "puppetserver" and "r10k" components of the Puppet Server
  ## use common storage. That common storage requirement might impose
  ## certain pod assignment scenarios. It might be required the "puppetserver" and "r10k"
  ## components to sit in the same K8s Node.
  ## For that matter optional pod affinity is made available for the "r10k" pod if need be.
  ## The exemplary configuration can be used without modification,
  ## if "Values.puppetserver.name" is kept unchanged.
  affinity: {}
  #  podAffinity:
  #    requiredDuringSchedulingIgnoredDuringExecution:
  #    - labelSelector:
  #        matchExpressions:
  #        - key: component
  #          operator: In
  #          values:
  #          - puppetserver
  #      topologyKey: "kubernetes.io/hostname"
  code:
    resources: {}
    #  requests:
    #    memory: 256Mi
    #    cpu: 250m
    #  limits:
    #    memory: 512Mi
    #    cpu: 500m
    cronJob:
      schedule: "*/15 * * * *"
      concurrencyPolicy: Forbid
      restartPolicy: Never
      startingDeadlineSeconds: 500
      activeDeadlineSeconds: 750
    ## Additional r10k code container arguments
    extraArgs: {}
    #  - --verbose=debug2   # error, warn, notice, info, debug, debug1, debug2
    #  - --trace
    #  - --color
    ## Additional puppetserver code container environment variables
    extraEnv: {}
    viaSsh:
      credentials:
        ssh:
          ## A multi-line string
          value:  # |
            #  PRIV_KEY CONTENTS
        known_hosts:
          ## A multi-line string
          value:  # |
            #  KNOWN_HOSTS CONTENTS
        ## Or set the git-sync Known Hosts file and SSH Private Key
        ## from a pre-existing K8s secret
        existingSecret: ""
  hiera:
    resources: {}
    #  requests:
    #    memory: 256Mi
    #    cpu: 250m
    #  limits:
    #    memory: 512Mi
    #    cpu: 500m
    cronJob:
      schedule: "*/2 * * * *"
      concurrencyPolicy: Forbid
      restartPolicy: Never
      startingDeadlineSeconds: 60
      activeDeadlineSeconds: 90
    ## Additional r10k hiera container arguments
    extraArgs: {}
    #  - --verbose=debug2   # error, warn, notice, info, debug, debug1, debug2
    #  - --trace
    #  - --color
    ## Additional puppetserver hiera container environment variables
    extraEnv: {}
    viaSsh:
      credentials:
        ssh:
          ## A multi-line string
          value:  # |
            #  PRIV_KEY CONTENTS
        known_hosts:
          ## A multi-line string
          value:  # |
            #  KNOWN_HOSTS CONTENTS
        ## Or set the git-sync Known Hosts file and SSH Private Key
        ## from a pre-existing K8s secret
        existingSecret: ""

## PostgreSQL Configuration for PuppetDB
##
postgres:
  name: postgres
  image: postgres
  tag: 9.6.16
  pullPolicy: IfNotPresent
  resources: {}
  #  requests:
  #    memory: 512Mi
  #    cpu: 500m
  #  limits:
  #    memory: 768Mi
  #    cpu: 750m
  ## Additional postgres container environment variables
  extraEnv: {}

## PuppetDB Configuration
##
puppetdb:
  name: puppetdb
  image: puppet/puppetdb
  tag: 6.9.0
  pullPolicy: IfNotPresent
  resources: {}
  #  requests:
  #    memory: 512Mi
  #    cpu: 500m
  #  limits:
  #    memory: 768Mi
  #    cpu: 750m
  ## Additional puppetdb container environment variables
  extraEnv: {}
  ## Credentials for PuppetDB and PostgreSQL
  credentials:
    username: puppetdb
    ## Override the 20-char random "password" in templates/puppetdb-secret.yaml
    password:
      value: ""
    # if used, the following existing secret must contain "username" and "password" keys, already base64 encoded.
    # using this secret supercedes all other credentials settings.
    existingSecret: ""


## Puppetboard Configuration
##
puppetboard:
  enabled: false
  name: puppetboard
  image: puppet/puppetboard
  tag: 0.3.0
  pullPolicy: IfNotPresent
  resources: {}
  #  requests:
  #    memory: 368Mi
  #    cpu: 300m
  #  limits:
  #    memory: 768Mi
  #    cpu: 500m
  ## Additional puppetboard container environment variables
  extraEnv: {}

## Hiera Configuration for Puppet Server
##
hiera:
  name: hiera
  hieradataurl: ""   # git@github.com:$SOMEUSER/hieradata.git
  ## If "hiera.config" is set, the pre-filled value of ":eyaml::datadir:",
  ## ":eyaml::pkcs7_private_key:" and ":eyaml::pkcs7_public_key:"
  ## must be kept unchanged.
  ## A multi-line string
  ##
  config:  # |-
  #  :backends:
  #    - eyaml
  #  :hierarchy:
  #    - common
  #  :eyaml:
  #    # Set branch name - e.g. "master", "%{::environment}", etc.
  #    :datadir: /etc/puppetlabs/code/hiera-data/[branch]   # keep base path unchanged.
  #    :extension: 'yaml'
  #    :pkcs7_private_key: /etc/puppetlabs/puppet/eyaml/private_key.pkcs7.pem   # keep unchanged
  #    :pkcs7_public_key:  /etc/puppetlabs/puppet/eyaml/public_key.pkcs7.pem   # keep unchanged
  eyaml:
    # choose using either a pre-existing configMap containing keys, or the private_key/public_key set
    existingMap: ""
    ## A multi-line string
    private_key:  # |
      #  PRIV_KEY CONTENTS
    ## A multi-line string
    public_key:  # |
      #  PUB_KEY CONTENTS

## Pod Configuration
##
## Node labels for pod assignment
nodeSelector:
  ## Common node labels for pod assignment
  allPods: {}
    # key: value
    #
  ## Node labels for pod assignment of "puppetserver" and "r10k" pods
  ## Note that the "puppetserver" and "r10k" components of the Puppet Server
  ## use common storage. That common storage requirement might impose
  ## certain pod assignment scenarios. It might be required the "puppetserver" and "r10k"
  ## components to sit in a common Cloud Provider's Availability Zone.
  ## For that matter separate node labels are made available for those if need be.
  commonStoragePods: {}
    # failure-domain.beta.kubernetes.io/zone: eu-central-1a
    # kubernetes.io/hostname: ip-10-0-6-168.eu-central-1.compute.internal

## Affinity for pod assignment
## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
affinity: {}

## Tolerations for pod assignment
## Ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
tolerations: []

## Leverage a priorityClass to ensure your pods survive resource shortages
## ref: https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/
# priorityClass: system-cluster-critical

## Extra Pod annotations
podAnnotations: {}

## Storage Configuration
##
storage:
  ## Puppet Server data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  ## Please check the `README.md` for more information
  ## regarding useful scenarios about "storageClass".
  storageClass: ""
  selector: false
  annotations: {}
  size: 100Mi
