---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: pupperware
spec:
  ports:
    - port: 5432
  selector:
    app: pupperware
    svc: postgres
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-claim
  labels:
    app: pupperware
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: pupperware
spec:
  selector:
    matchLabels:
      app: pupperware
      svc: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pupperware
        svc: postgres
    spec:
      hostname: postgres
      containers:
        - image: puppet/puppetdb-postgres
          name: postgres
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: puppetdb
                  key: password
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: puppetdb
                  key: user
          ports:
            - name: postgres
              containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data/
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-claim
