---
apiVersion: v1
kind: Service
metadata:
  name: puppet
  labels:
    app: pupperware
spec:
  ports:
    - port: 8140
  selector:
    app: pupperware
    svc: puppet
  type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: puppet-code-claim
  labels:
    app: pupperware
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: puppet-serverdata-claim
  labels:
    app: pupperware
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: puppet-puppet-claim
  labels:
    app: pupperware
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: puppet
  labels:
    app: pupperware
spec:
  selector:
    matchLabels:
      app: pupperware
      svc: puppet
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pupperware
        svc: puppet
    spec:
      hostname: puppet.internal
      containers:
        - image: puppet/puppetserver
          name: puppet
          env:
            # necessary to set certname and server in puppet.conf, required by
            # puppetserver ca cli application
            - name: PUPPETSERVER_HOSTNAME
              value: puppet.internal
            - name: DNS_ALT_NAMES
              value: puppet,puppet.internal
            - name: PUPPETDB_SERVER_URLS
              value: https://puppetdb.internal:8081
          ports:
            - containerPort: 8140
          volumeMounts:
            - name: puppet-code-storage
              mountPath: /etc/puppetlabs/code/
            - name: puppet-puppet-storage
              mountPath: /etc/puppetlabs/puppet/
            - name: puppet-serverdata-storage
              mountPath: /opt/puppetlabs/server/data/puppetserver/
      volumes:
        - name: puppet-code-storage
          persistentVolumeClaim:
            claimName: puppet-code-claim
        - name: puppet-puppet-storage
          persistentVolumeClaim:
            claimName: puppet-puppet-claim
        - name: puppet-serverdata-storage
          persistentVolumeClaim:
            claimName: puppet-serverdata-claim
