{{- if .Values.puppetserver.multiCompilers.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: init-compilers-config
  labels:
    {{- include "puppetserver.puppetserver.labels" . | nindent 4 }}
data:
  check_for_compilers.sh: |
    #!/usr/bin/env bash
    if [[ -d "$PUPPET_DATA_DIR" ]]; then
        echo "A Puppetserver master has already started running."
        echo "Waiting to finish the generation of the Puppet SSL certs..."
        sleep 5
        while [[ ! -f "$PUPPET_SSL_CERT_PEM" ]];
            do
              echo "Still waiting..."
              sleep 5
            done
        sleep 60
        echo "Puppet SSL certs have been generated. Continuing..."
    else
        echo "No other Puppetserver master is running. Continuing..."
    fi
{{- end }}
