{{- if and (.Values.hiera.hieradataurl) (not .Values.r10k.hiera.viaSsh.credentials.existingSecret) }}
{{- if and (.Values.r10k.hiera.viaSsh.credentials.ssh.value) (.Values.r10k.hiera.viaSsh.credentials.known_hosts.value) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "r10k.hiera.secret" . }}
  labels:
    {{- include "puppetserver.r10k.labels" . | nindent 4 }}
type: Opaque
data:
{{- with .Values.r10k.hiera.viaSsh.credentials }}
{{- if and (.ssh.value) (.known_hosts.value) }}
  id_rsa: {{ .ssh.value | b64enc | quote }}
  known_hosts: {{ .known_hosts.value | b64enc | quote }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
