{{- if .Values.puppetserver.puppeturl }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ template "puppetserver.name" . }}-r10k-code-deploy
  labels:
    {{- include "puppetserver.r10k.labels" . | nindent 4 }}
spec:
{{- with .Values.r10k.code.cronJob }}
  schedule: "{{.schedule}}"
{{- if .concurrencyPolicy }}
  concurrencyPolicy: {{ .concurrencyPolicy }}
{{- end }}
{{- if .startingDeadlineSeconds }}
  startingDeadlineSeconds: {{ .startingDeadlineSeconds }}
{{- end }}
{{- end }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "puppetserver.r10k.labels" . | nindent 12 }}
        {{- if .Values.podAnnotations }}
          annotations:
            {{- toYaml .Values.podAnnotations | nindent 12 }}
        {{- end }}
        spec:
          containers:
            - name: r10k-code
              image: "{{.Values.r10k.image}}:{{.Values.r10k.tag}}"
              imagePullPolicy: "{{.Values.r10k.pullPolicy}}"
              resources:
                {{- toYaml .Values.r10k.code.resources | nindent 16 }}
              env:
              {{- range $key, $value := .Values.r10k.code.extraEnv }}
                - name: "{{ $key }}"
                  value: "{{ $value }}"
              {{- end }}
              args:
                - deploy
                - environment
                - --config
                - /etc/puppetlabs/puppet/r10k.yaml
                - --puppetfile
              {{- range $key, $value := .Values.r10k.code.extraArgs }}
                - {{ $value }}
              {{- end }}
              volumeMounts:
              {{- with .Values.r10k.code.viaSsh.credentials }}
              {{- if or (.existingSecret) (and (.ssh.value) (.known_hosts.value)) }}
                - name: r10k-code-secret
                  mountPath: /home/puppet/.ssh
              {{- end }}
              {{- end }}
                - name: r10k-volume
                  mountPath: /etc/puppetlabs/puppet/r10k.yaml
                  subPath: r10k.yaml
                - name: puppet-code-storage
                  mountPath: /etc/puppetlabs/code/
          securityContext:
            runAsUser: 999   # "puppet" UID
            runAsGroup: 999 # "puppet" GID
            fsGroup: 999   # "puppet" GID
        {{- with .Values.r10k.code.cronJob }}
        {{- if .restartPolicy }}
          restartPolicy: {{ .restartPolicy }}
        {{- end }}
        {{- if .activeDeadlineSeconds }}
          activeDeadlineSeconds: {{ .activeDeadlineSeconds }}
        {{- end }}
        {{- end }}
          volumes:
            - name: puppet-code-storage
              persistentVolumeClaim:
                claimName: puppet-code-claim
            - name: r10k-volume
              configMap:
                name: r10k-code-config
          {{- if or (.Values.r10k.code.viaSsh.credentials.existingSecret) (and (.Values.r10k.code.viaSsh.credentials.ssh.value) (.Values.r10k.code.viaSsh.credentials.known_hosts.value)) }}
            - name: r10k-code-secret
              secret:
                secretName: {{ template "r10k.code.secret" . }}
                defaultMode: 288 # = mode 0440
          {{- end }}
        {{- if (or (.Values.nodeSelector.allPods) (.Values.nodeSelector.commonStoragePods)) }}
          nodeSelector:
          {{- if (.Values.nodeSelector.allPods) }}
            {{ toYaml .Values.nodeSelector.allPods | nindent 14 }}
          {{- end }}
          {{- if (.Values.nodeSelector.commonStoragePods) }}
            {{ toYaml .Values.nodeSelector.commonStoragePods | nindent 14 }}
          {{- end }}
        {{- end }}
        {{- if .Values.r10k.affinity }}
          affinity:
            {{ toYaml .Values.r10k.affinity | nindent 14 }}
        {{- else if .Values.affinity }}
          affinity:
            {{ toYaml .Values.affinity | nindent 14 }}
        {{- end }}
        {{- if .Values.tolerations }}
          tolerations:
            {{ toYaml .Values.tolerations| nindent 14 }}
        {{- end }}
        {{- if and (.Capabilities.APIVersions.Has "scheduling.k8s.io/v1beta1") (.Values.priorityClassName) }}
          priorityClassName: {{ .Values.priorityClassName }}
        {{- end }}
{{- end }}
