{{- if .Values.hiera.hieradataurl }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: r10k-hiera-config
  labels:
    {{- include "puppetserver.r10k.labels" . | nindent 4 }}
data:
  r10k.yaml: |
    # The location to use for storing cached Git repos
    :cachedir: '/etc/puppetlabs/code/r10k_cache'

    # A list of git repositories to create
    :sources:
      # This will clone the git repository and instantiate an environment per
      # branch in '/etc/puppetlabs/code/hiera-data'
      :hiera_repo:
        remote: '{{.Values.hiera.hieradataurl}}'
        basedir: '/etc/puppetlabs/code/hiera-data'

    :git:
      provider: 'rugged' # Either 'shellgit' or 'rugged', defaults to 'shellgit'
    {{- with .Values.r10k.hiera.viaSsh.credentials }}
    {{- if or (.existingSecret) (and (.ssh.value) (.known_hosts.value)) }}
      private_key: '/root/.ssh/id_rsa'
    {{- end }}
    {{- end }}
      repositories:
        - remote: '{{.Values.hiera.hieradataurl}}'
{{- end }}

